mySQL:
  host: localhost
  port: 3306
  user: root
  password: root
  database: dailyquest

#每日任务次数的限制
accept:
  #default组，所有人默认的限制
  default: 2
  #以下组可以自定义
  #权限: dailyquest.accept.<name>
  vip1: 3
  builder: 5

stage1:
  monsters:
  - ZOMBIE
  - SKELETON
  minNum: 5
  maxNum: 20
stage2:
  ores:
  - COAL_ORE
  - DIAMOND_ORE
  - EMERALD_ORE
  - IRON_ORE
  - LAPIS_ORE
  - QUARTZ_ORE
  - REDSTONE_ORE
  - GOLD_ORE
  minNum: 7
  maxNum: 10
stage3:
  world: world
  radius: 300

reward:
- give %player% diamond 1;give %player% stone 64;5
- give %player% diamond 10;2
- give %player% gold_block 2;2
- give %player% emerald 10;1