mySQL:
  host: localhost
  port: 3306
  user: root
  password: root
  database: dailyquest

stage1:
  monsters:
  - ZOMBIE
  - SKELETON
  minNum: 5
  maxNum: 20
stage2:
  ores:
  - COAL_ORE
  - DIAMOND_ORE
  - EMERALD_ORE
  - IRON_ORE
  - LAPIS_ORE
  - QUARTZ_ORE
  - REDSTONE_ORE
  - GOLD_ORE
  minNum: 7
  maxNum: 10
stage3:
  world: world
  radius: 300

reward:
- DIAMOND 3
- IRON 5
- STONE 32
- DIRT 64